# PatentMarker 2025 Installer (PowerShell)
# Target: AutoCAD 2025/2026+ (R25.0+)
# Requires: Windows 10+, PowerShell 5.1+
# Encoding: UTF-8 with BOM (readable by both PS 5.1 and PS 7)

[CmdletBinding()]
param(
    [string]$DllPath = "",
    [switch]$NoPause
)

$ErrorActionPreference = "Stop"
$script:ExitCode = 0
$script:Installed = 0
$script:ScriptDir = $PSScriptRoot
$script:LogPath = Join-Path $script:ScriptDir "install-2025.log"
$script:FallbackLspPath = $null

function Initialize-InstallerLog {
    $line = "$(Get-Date -Format s) START"
    try {
        Add-Content -LiteralPath $script:LogPath -Value $line -Encoding UTF8 -ErrorAction Stop
    }
    catch {
        $script:LogPath = Join-Path $env:TEMP "PatentMarker-2025-install.log"
        try { Add-Content -LiteralPath $script:LogPath -Value $line -Encoding UTF8 -ErrorAction SilentlyContinue } catch { }
    }
}

function Write-InstallerLog {
    param([string]$Message)
    try { Add-Content -LiteralPath $script:LogPath -Value "$(Get-Date -Format s) $Message" -Encoding UTF8 -ErrorAction SilentlyContinue } catch { }
}

function Write-InstallerLine {
    param(
        [string]$Message,
        [ConsoleColor]$Color
    )
    if ($PSBoundParameters.ContainsKey("Color")) {
        Write-Host $Message -ForegroundColor $Color
    }
    else {
        Write-Host $Message
    }
    Write-InstallerLog $Message
}

# === Internationalization (i18n) ===
function Get-SysLang {
    try {
        $lid = (Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\Language" -Name InstallLanguage -ErrorAction SilentlyContinue).InstallLanguage
        if (-not $lid) { $lid = (Get-ItemProperty "HKLM:\SYSTEM\CurrentControlSet\Control\Nls\Language" -Name Default -ErrorAction SilentlyContinue).Default }
        if (-not $lid) { $lid = "0804" }
    }
    catch { $lid = "0804" }
    if ($lid -in "0804", "0404", "0C04", "1404", "7C04") { return "zh" }
    return "en"
}
$script:Lang = Get-SysLang

function L {
    param([string]$en, [string]$zh)
    if ($script:Lang -eq "zh") { return $zh }
    return $en
}
# === End i18n ===

function Set-RegistryValue {
    param(
        [string]$Path,
        [string]$Name,
        [object]$Value,
        [ValidateSet("String", "DWord")]
        [string]$PropertyType = "String"
    )
    # New-ItemProperty makes the registry value type explicit, and -Force
    # also handles an existing value with the wrong registry type.
    New-ItemProperty -LiteralPath $Path -Name $Name -Value $Value -PropertyType $PropertyType -Force | Out-Null
}

function New-LspFallback {
    param([string]$PluginDll)

    $escapedDll = $PluginDll.Replace("\", "\\").Replace('"', '\"')
    $content = @'
; PatentMarker 2025 fallback loader. Generated by install-2025.ps1.
; Load this file with AutoCAD APPLOAD, or add it to the Startup Suite.
(defun c:PATENTMARKER-LOAD (/ dllPath oldFileDia)
  (setq dllPath "__PATENTMARKER_DLL__")
  (setq oldFileDia (getvar "FILEDIA"))
  (setvar "FILEDIA" 0)
  (command "_.NETLOAD" dllPath)
  (setvar "FILEDIA" oldFileDia)
  (princ "\nPatentMarker NETLOAD attempted. Use BZ to open the palette.")
  (princ)
)
(PATENTMARKER-LOAD)
(princ)
'@.Replace("__PATENTMARKER_DLL__", $escapedDll)

    $candidates = @(
        (Join-Path $script:ScriptDir "load-patent-marker.lsp"),
        (Join-Path (Join-Path $env:LOCALAPPDATA "PatentMarker") "load-patent-marker.lsp")
    )
    foreach ($path in $candidates) {
        try {
            $parent = Split-Path -Parent $path
            if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
            [IO.File]::WriteAllText($path, $content, (New-Object Text.UTF8Encoding($false)))
            if (Test-Path -LiteralPath $path) {
                $script:FallbackLspPath = $path
                Write-InstallerLine (L "LSP fallback generated: $path" "已生成 LSP 兜底文件：$path") -Color Green
                return $path
            }
        }
        catch {
            Write-InstallerLine (L "Could not write LSP fallback at $path : $($_.Exception.Message)" "无法在 $path 写入 LSP 兜底文件：$($_.Exception.Message)") -Color Yellow
        }
    }
    throw (L "Could not generate an LSP fallback file." "无法生成 LSP 兜底文件。")
}

Initialize-InstallerLog

try {
    Write-InstallerLine "========================================"
    Write-InstallerLine (L "PatentMarker 2025 Installer" "PatentMarker 2025 安装程序")
    Write-InstallerLine (L "(AutoCAD 2025/2026+)" "（AutoCAD 2025/2026+）")
    Write-InstallerLine "========================================"
    Write-InstallerLine (L "Log: $script:LogPath" "日志：$script:LogPath")

    # 1. Locate DLL
    if ([string]::IsNullOrEmpty($DllPath)) {
        $DllPath = Join-Path $script:ScriptDir "PatentMarker.dll"
    }
    $DllPath = [IO.Path]::GetFullPath($DllPath)
    if (-not (Test-Path -LiteralPath $DllPath -PathType Leaf)) {
        throw (L "PatentMarker.dll not found at: $DllPath" "找不到 PatentMarker.dll，路径：$DllPath")
    }
    Write-InstallerLine "DLL: $DllPath"

    # Always create a manual fallback before touching the registry. This keeps
    # the installer useful even when AutoCAD is not registered or HKCU writes
    # are blocked by policy.
    New-LspFallback $DllPath | Out-Null

    # 2. Find AutoCAD 2025+ in either registry hive
    $acadVersions = @("R25.0", "R25.1", "R26.0")
    $detectedBaseKey = $null
    $registryWriteBase = $null
    $foundVersion = ""
    $subKeys = @()

    foreach ($ver in $acadVersions) {
        $candidates = @(
            "HKCU:\Software\Autodesk\AutoCAD\$ver",
            "HKLM:\Software\Autodesk\AutoCAD\$ver"
        )
        foreach ($candidate in $candidates) {
            if (-not (Test-Path -LiteralPath $candidate)) { continue }
            $candidateSubKeys = @(Get-ChildItem -LiteralPath $candidate -ErrorAction SilentlyContinue | Where-Object { $_.PSChildName -like "ACAD-*" })
            if ($candidateSubKeys.Count -gt 0) {
                $detectedBaseKey = $candidate
                $subKeys = $candidateSubKeys
                $foundVersion = $ver
                break
            }
        }
        if ($null -ne $detectedBaseKey) { break }
    }

    if ($null -eq $detectedBaseKey) {
        Write-InstallerLine (L "WARNING: AutoCAD 2025+ was not found in registry." "警告：注册表中未找到 AutoCAD 2025+。") -Color Yellow
        Write-InstallerLine (L "Use APPLOAD with the generated LSP fallback below." "请使用下面生成的 LSP 兜底文件，通过 APPLOAD 手动加载。") -Color Yellow
    }
    else {
        Write-InstallerLine (L "Found: $foundVersion ($detectedBaseKey)" "找到：$foundVersion（$detectedBaseKey）")

        # Always write the application registration to HKCU. The old script
        # attempted to write to HKLM when detection found an HKLM key, which
        # silently failed for normal users. HKCU is the supported no-admin path.
        $registryWriteBase = "HKCU:\Software\Autodesk\AutoCAD\$foundVersion"
        foreach ($sk in $subKeys) {
            $acadUserKey = Join-Path $registryWriteBase $sk.PSChildName
            $appKey = Join-Path $acadUserKey "Applications\PatentMarker"
            try {
                if (-not (Test-Path -LiteralPath $acadUserKey)) { New-Item -Path $acadUserKey -Force | Out-Null }
                if (-not (Test-Path -LiteralPath $appKey)) { New-Item -Path $appKey -Force | Out-Null }
                Set-RegistryValue $appKey "DESCRIPTION" "PatentMarker - Patent Drawing Annotation Plugin" "String"
                Set-RegistryValue $appKey "LOADCTRLS" 14 "DWord"
                Set-RegistryValue $appKey "MANAGED" 1 "DWord"
                Set-RegistryValue $appKey "LOADER" $DllPath "String"

                $verify = Get-ItemProperty -LiteralPath $appKey -ErrorAction Stop
                if ([string]$verify.LOADER -eq $DllPath -and [int]$verify.LOADCTRLS -eq 14 -and [int]$verify.MANAGED -eq 1) {
                    Write-InstallerLine "  $($sk.PSChildName): $(L 'Registry OK' '注册表 OK')" -Color Green
                    $script:Installed++
                }
                else {
                    Write-InstallerLine "  $($sk.PSChildName): $(L 'Registry verification failed' '注册表校验失败')" -Color Yellow
                }
            }
            catch {
                Write-InstallerLine "  $($sk.PSChildName): $(L 'FAILED' '失败') - $($_.Exception.Message)" -Color Yellow
            }
        }
    }

    # 3. Summary
    Write-InstallerLine ""
    Write-InstallerLine (L "=== Summary ===" "=== 摘要 ===")
    Write-InstallerLine (L "Registry entries: $script:Installed" "注册表条目：$script:Installed")
    Write-InstallerLine (L "LSP fallback: $script:FallbackLspPath" "LSP 兜底文件：$script:FallbackLspPath")
    Write-InstallerLine ""
    if ($script:Installed -gt 0) {
        Write-InstallerLine (L ">>> Restart AutoCAD 2025+." ">>> 请重启 AutoCAD 2025+。") -Color Green
        Write-InstallerLine (L ">>> PatentMarker will auto-load." ">>> PatentMarker 将自动加载。")
    }
    else {
        Write-InstallerLine (L ">>> Auto-load registration was not completed." ">>> 自动加载注册未完成。") -Color Yellow
        Write-InstallerLine (L ">>> In AutoCAD, run APPLOAD and select the LSP fallback, or run NETLOAD on:" ">>> 在 AutoCAD 中运行 APPLOAD 选择 LSP 兜底文件，或对下面 DLL 运行 NETLOAD：") -Color Yellow
        Write-InstallerLine "    $DllPath"
    }
    Write-InstallerLine (L "Commands: BZ BZM BZC BZA BZS" "命令：BZ(面板) BZM(标注) BZC(检查) BZA(对齐) BZS(全选)")
    Write-InstallerLine "========================================"
}
catch {
    $script:ExitCode = 1
    $message = $_.Exception.Message
    Write-InstallerLine (L "ERROR: $message" "错误：$message") -Color Red
    Write-InstallerLine (L "The installer stopped. See the log: $script:LogPath" "安装程序已停止。请查看日志：$script:LogPath") -Color Red
}
finally {
    if (-not $NoPause -and $Host.Name -eq "ConsoleHost") {
        Write-Host ""
        Read-Host (L "Press Enter to close" "按 Enter 键关闭") | Out-Null
    }
}

if ($script:ExitCode -ne 0) { exit $script:ExitCode }
